variable "vpc_id" {}
variable "my_ip" {}
variable "env_prefix" {}
variable "instance_type" {}
variable "public_key_location" {}
variable "virtualization-type" {}
variable "architecture" {}
variable "avail_zone" {}
variable "subnet_id" {}